### ISSUE TITLE
cant run it

### ISSUE THREAD

**Issue by jasonkack** [MxLinux/pypotd#1]
```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    generate()
  File "/home/mrjake/.local/lib/python3.6/site-packages/pypotd/__init__.py", line 8, in generate
    potd_date = date.fromisoformat(str(potd_date))
AttributeError: type object 'datetime.date' has no attribute 'fromisoformat'
```
code is from your example
`
from pypotd import generate

generate()
`
Python 3.6.9

**Comment by MxLinux** [comment]
Unfortunately it looks like I mislabeled the project on its pypi page. `fromisoformat` was added in 3.7.
